In [2]:
import pandas as pd
import numpy as np
import regex as re
from io import StringIO

In [32]:
pd_csv = pd.read_csv("output-0-pandas.csv")

In [33]:
pd_csv.head(5)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11
0,2,"HMS Income Fund, Inc. Condensed Consolidated ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,"As of June 30, 2015",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value,NaN,NaN,NaN,NaN,NaN,NaN
3,6,Control Investments (6),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",NaN,8147,NaN,NaN,7996.0,NaN,NaN,7996.0,NaN

In [34]:
pd_csv = pd_csv.iloc[:,1:]

In [35]:
pd_csv

,0,1,2,3,4,5,6,7,8,9,10,11
0,"HMS Income Fund, Inc. Condensed Consolidated ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"As of June 30, 2015",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value,NaN,NaN,NaN,NaN,NaN,NaN
3,Control Investments (6),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",NaN,8147,NaN,NaN,7996.0,NaN,NaN,7996.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
146,NaN,NaN,NaN,NaN,13410,NaN,13410.0,NaN,NaN,NaN,NaN,NaN
147,"Worley Claims Services, LLC (8) (11)",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,NaN,6409,NaN,6500.0,NaN,NaN,NaN,NaN
148,YP Holdings LLC (8),Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,NaN,2687,NaN,2694.0,NaN,NaN,NaN,NaN
149,Subtotal Non-Control/Non-Affiliate Investments...,NaN,NaN,736957,NaN,NaN,729987.0,NaN,NaN,NaN,NaN,NaN
150,Total Investments,NaN,NaN,NaN,NaN,760090,NaN,NaN,754155.0,NaN,NaN,NaN

In [36]:
pd_csv.reset_index()

,index,0,1,2,3,4,5,6,7,8,9,10,11
0,0,"HMS Income Fund, Inc. Condensed Consolidated ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"As of June 30, 2015",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Control Investments (6),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",NaN,8147,NaN,NaN,7996.0,NaN,NaN,7996.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,146,NaN,NaN,NaN,NaN,13410,NaN,13410.0,NaN,NaN,NaN,NaN,NaN
147,147,"Worley Claims Services, LLC (8) (11)",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,NaN,6409,NaN,6500.0,NaN,NaN,NaN,NaN
148,148,YP Holdings LLC (8),Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,NaN,2687,NaN,2694.0,NaN,NaN,NaN,NaN
149,149,Subtotal Non-Control/Non-Affiliate Investments...,NaN,NaN,736957,NaN,NaN,729987.0,NaN,NaN,NaN,NaN,NaN
150,150,Total Investments,NaN,NaN,NaN,NaN,760090,NaN,NaN,754155.0,NaN,NaN,NaN

In [59]:
for col in pd_csv.columns:
    portfolio_index_list = pd_csv.index[pd_csv[col].astype(str).str.contains("Portfolio Company")].to_list()
    break

In [60]:
portfolio_index = portfolio_index_list[0]

In [61]:
portfolio_index

2

In [62]:
pd_csv = pd_csv.iloc[portfolio_index:]

In [63]:
pd_csv

,0,1,2,3,4,5,6,7,8,9,10,11
2,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value,NaN,NaN,NaN,NaN,NaN,NaN
3,Control Investments (6),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",NaN,8147,NaN,NaN,7996.0,NaN,NaN,7996.0,NaN
5,NaN,NaN,"Member Units (2,896 shares)",NaN,6435,NaN,6435.0,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,14431,NaN,14431.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
146,NaN,NaN,NaN,NaN,13410,NaN,13410.0,NaN,NaN,NaN,NaN,NaN
147,"Worley Claims Services, LLC (8) (11)",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,NaN,6409,NaN,6500.0,NaN,NaN,NaN,NaN
148,YP Holdings LLC (8),Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,NaN,2687,NaN,2694.0,NaN,NaN,NaN,NaN
149,Subtotal Non-Control/Non-Affiliate Investments...,NaN,NaN,736957,NaN,NaN,729987.0,NaN,NaN,NaN,NaN,NaN
150,Total Investments,NaN,NaN,NaN,NaN,760090,NaN,NaN,754155.0,NaN,NaN,NaN

In [1098]:
for i in range(2,pd_csv.shape[0]):
    for j in range(pd_csv.shape[1]):
        row_alphabet_check = False
        if(pd.isnull(pd_csv.iat[i,j])):
            #print("Index",i,j)
            if(i>0):
                #print(pd_csv.iat[i-1,j])
                if(pd.isnull(pd_csv.iat[i-1,j])):
                    1
                else:
                    if(re.search('[a-zA-Z]', str(pd_csv.iat[i-1,j]))):
                        for k in range(pd_csv.shape[1]):
                            if(re.search('[a-zA-Z]', str(pd_csv.iat[i,k])) and pd.notnull(pd_csv.iat[i,k])):
                                #print("Alpha Check",pd_csv.iat[i,k])
                                row_alphabet_check = True
                                break
                        if(row_alphabet_check):
                            #print(pd_csv.iat[i-1,j])
                            pd_csv.iat[i,j] = pd_csv.iat[i-1,j]

In [1099]:
pd_csv

,0,1,2,3,4,5,6,7,8,9,10,11
2,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value,NaN,NaN,NaN,NaN,NaN,NaN
3,Control Investments (6),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",NaN,8147,NaN,NaN,7996.0,NaN,NaN,7996.0,NaN
5,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",NaN,6435,NaN,6435.0,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,14431,NaN,14431.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
146,NaN,NaN,NaN,NaN,13410,NaN,13410.0,NaN,NaN,NaN,NaN,NaN
147,"Worley Claims Services, LLC (8) (11)",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,NaN,6409,NaN,6500.0,NaN,NaN,NaN,NaN
148,YP Holdings LLC (8),Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,NaN,2687,NaN,2694.0,NaN,NaN,NaN,NaN
149,Subtotal Non-Control/Non-Affiliate Investments...,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",736957,NaN,NaN,729987.0,NaN,NaN,NaN,NaN,NaN
150,Total Investments,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",NaN,NaN,760090,NaN,NaN,754155.0,NaN,NaN,NaN

In [1100]:
pd_csv= pd.read_csv(StringIO(re.sub(',+',',',pd_csv.to_csv())))

In [1101]:
pd_csv.head(40)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11
0,2,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value,NaN,NaN,NaN,NaN,NaN,NaN
1,3,Control Investments (6),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0,NaN,NaN,NaN,NaN,NaN,NaN
3,5,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,14431,14431.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,7,Subtotal Control Investments (6) (2% of total ...,14431,14431.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,8,Affiliate Investments (4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,9,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,11.00% Secured Debt (Maturity Date -November 7...,3040,2913.0,2913.0,NaN,NaN,NaN,NaN,NaN,NaN
8,10,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,Member Units (46 shares),300,300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,11,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,Warrants (10 equivalent shares),65,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,12,3278,3278.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,13,"Mystic Logistics, Inc. (10) (13)",Logistics and Distribution Services Provider f...,"12.00% Secured Debt (Maturity Date -August 15,...",2500,2430,2500.0,NaN,NaN,NaN,NaN,NaN,NaN
12,14,"Mystic Logistics, Inc. (10) (13)",Logistics and Distribution Services Provider f...,"Common Stock (1,468 shares)",680,1645.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,15,3110,4145.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,16,SoftTouch Medical Holdings LLC (8) (10) (13),Home Provider of Pediatric Durable Medical Equ...,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",1470,1444,1444.0,NaN,NaN,NaN,NaN,NaN,NaN
15,17,SoftTouch Medical Holdings LLC (8) (10) (13),Home Provider of Pediatric Durable Medical Equ...,Member Units (798 shares) (16),870,870.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,18,2314,2314.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,19,Subtotal Affiliate Investments (4) (1% of tota...,8702,9737.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,20,Non-Control/Non-Affiliate Investments (5),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,21,Ability Network Inc. (8),Health Care Information Technology,"LIBOR Plus 5.00% (Floor 1.00%), Current Coupon...",4950,4902.0,4971.0,NaN,NaN,NaN,NaN,NaN,NaN
20,22,Allflex Holdings III Inc. (8),Manufacturer of Livestock Identification Products,"LIBOR Plus 7.00% (Floor 1.00%), Current Coupon...",12422,12514,12519.0,NaN,NaN,NaN,NaN,NaN,NaN
21,23,"AmeriTech College Operations, LLC (10) (13)",For-Profit Nursing and Healthcare College,"10.00% Secured Debt, (Maturity - January 31, 2...",610,609,543.0,NaN,NaN,NaN,NaN,NaN,NaN
22,24,"AMF Bowling Centers, Inc. (8)",Bowling Alley Operator,"LIBOR Plus 6.25% (Floor 1.00%), Current Coupon...",10918,10826,10958.0,NaN,NaN,NaN,NaN,NaN,NaN
23,25,"AP Gaming I, LLC (8) (11)","Developer, Manufacturer, and Operator of Gamin...","LIBOR Plus 8.25% (Floor 1.00%), Current Coupon...",7481,7406,7471.0,NaN,NaN,NaN,NaN,NaN,NaN
24,26,"Aptean, Inc. (8)",Enterprise Application Software Provider,"LIBOR Plus 4.25% (Floor 1.00%), Current Coupon...",4438,4437,4399.0,NaN,NaN,NaN,NaN,NaN,NaN
25,27,"Arcus Hunting, LLC (8) (11)","Deer Lures, Attractants and Scent Elimination ...","LIBOR Plus 7.00% (Floor 1.00%), Current Coupon...",4933,4817,4817.0,NaN,NaN,NaN,NaN,NaN,NaN
26,28,"Artel, LLC (8)",Land-Based and Commercial Satellite Provider,"LIBOR Plus 6.00% (Floor 1.25%), Current Coupon...",4282,4172,4185.0,NaN,NaN,NaN,NaN,NaN,NaN
27,29,ATX Networks Corp. (8) (9) (12),Provider of Radio Frequency Management Equipment,"LIBOR Plus 6.00% (Floor 1.00%), Current Coupon...",15000,14700,14700.0,NaN,NaN,NaN,NaN,NaN,NaN
28,30,"Berry Aviation, Inc. (11)",Charter Airline Services,12.00% Current / 1.75% PIK Secured Debt (Matur...,1407,1384,1384.0,NaN,NaN,NaN,NaN,NaN,NaN
29,31,"Berry Aviation, Inc. (11)",Charter Airline Services,Common Stock (138 shares),100,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,32,1484,1484.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,33,"Bioventus, LLC (8) (11)",Production of Orthopedic Healing Products,"LIBOR Plus 10.00% (Floor 1.00%), Current Coupo...",7000,6877,7000.0,NaN,NaN,NaN,NaN,NaN,NaN
32,34,Blackbrush Oil and Gas LP (8),Oil & Gas Exploration,"LIBOR Plus 6.50% (Floor 1.00%), Current Coupon...",12085,11627,11224.0,NaN,NaN,NaN,NaN,NaN,NaN
33,35,Blackhawk Specialty Tools LLC (8) (12),Oilfield Equipment & Services,"LIBOR Plus 5.25% (Floor 1.25%), Current Coupon...",8639,8131,8380.0,NaN,NaN,NaN,NaN,NaN,NaN
34,36,Blue Bird Body Company (8),School Bus Manufacturer,"LIBOR Plus 5.50% (Floor 1.00%), Current Coupon...",5850,5775,5865.0,NaN,NaN,NaN,NaN,NaN,NaN
35,37,"Bluestem Brands, Inc. (8)",Multi-Channel Retailer of General Merchandise,"LIBOR Plus 7.50% (Floor 1.00%), Current Coupon...",6981,6725,6968.0,NaN,NaN,NaN,NaN,NaN,NaN
36,38,"Brightwood Capital Fund III, LP (9) (15)",Investment Partnership,"LP Interests (Brightwood Capital Fund III, LP)...",2825,2825.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,39,"Brundage-Bone Concrete Pumping, Inc.",Construction Services Provider,"10.38% Secured Bond (Maturity - September 1, 2...",4000,4045,4160.0,NaN,NaN,NaN,NaN,NaN,NaN
38,40,"Buca C, LLC (8) (10) (13)",Restaurants,"LIBOR Plus 7.25% (Floor 1.00%), Current Coupon...",16800,16464,16464.0,NaN,NaN,NaN,NaN,NaN,NaN
39,41,"Buca C, LLC (8) (10) (13)",Restaurants,Member Units (4 units),2400,2400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1102]:
perc = 100 # Like N %
min_count =  int(((100-perc)/100)*pd_csv.shape[0] + 1)
pd_csv = pd_csv.dropna( axis=1, 
                thresh=min_count)

In [1103]:
pd_csv

,Unnamed: 0,0,1,2,3,4,5
0,2,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value
1,3,Control Investments (6),NaN,NaN,NaN,NaN,NaN
2,4,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0
3,5,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,NaN
4,6,14431,14431.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
144,146,13410,13410.0,NaN,NaN,NaN,NaN
145,147,"Worley Claims Services, LLC (8) (11)",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,6409,6500.0
146,148,YP Holdings LLC (8),Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,2687,2694.0
147,149,Subtotal Non-Control/Non-Affiliate Investments...,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",736957,729987.0,NaN
148,150,Total Investments,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",760090,754155.0,NaN

In [1104]:
new_header = pd_csv.iloc[0]  # grab the first row for the header
pd_csv = pd_csv[1:]  # take the data less the header row
pd_csv.columns = new_header  # set the header row as the df header

Unnamed: 0                             2
0              Portfolio Company (1) (3)
1                   Business Description
2             Type of Investment (2) (3)
3                          Principal (7)
4                               Cost (7)
5                             Fair Value
Name: 0, dtype: object

In [1105]:
pd_csv

,2,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value
1,3,Control Investments (6),NaN,NaN,NaN,NaN,NaN
2,4,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0
3,5,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,NaN
4,6,14431,14431.0,NaN,NaN,NaN,NaN
5,7,Subtotal Control Investments (6) (2% of total ...,14431,14431.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
144,146,13410,13410.0,NaN,NaN,NaN,NaN
145,147,"Worley Claims Services, LLC (8) (11)",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,6409,6500.0
146,148,YP Holdings LLC (8),Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,2687,2694.0
147,149,Subtotal Non-Control/Non-Affiliate Investments...,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",736957,729987.0,NaN
148,150,Total Investments,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",760090,754155.0,NaN

In [1106]:
pd_csv.reset_index()

,index,2,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value
0,1,3,Control Investments (6),NaN,NaN,NaN,NaN,NaN
1,2,4,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0
2,3,5,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,NaN
3,4,6,14431,14431.0,NaN,NaN,NaN,NaN
4,5,7,Subtotal Control Investments (6) (2% of total ...,14431,14431.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
143,144,146,13410,13410.0,NaN,NaN,NaN,NaN
144,145,147,"Worley Claims Services, LLC (8) (11)",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,6409,6500.0
145,146,148,YP Holdings LLC (8),Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,2687,2694.0
146,147,149,Subtotal Non-Control/Non-Affiliate Investments...,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",736957,729987.0,NaN
147,148,150,Total Investments,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",760090,754155.0,NaN

In [1107]:
pd_csv = pd_csv.iloc[: , 1:]

In [1108]:
pd_csv = pd_csv.replace("~",",",regex=True)

In [1109]:
pd_csv.head(40)

,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value
1,Control Investments (6),NaN,NaN,NaN,NaN,NaN
2,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0
3,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,NaN
4,14431,14431.0,NaN,NaN,NaN,NaN
5,Subtotal Control Investments (6) (2% of total ...,14431,14431.0,NaN,NaN,NaN
6,Affiliate Investments (4),NaN,NaN,NaN,NaN,NaN
7,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,11.00% Secured Debt (Maturity Date -November 7...,3040,2913.0,2913.0
8,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,Member Units (46 shares),300,300.0,NaN
9,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,Warrants (10 equivalent shares),65,65.0,NaN
10,3278,3278.0,NaN,NaN,NaN,NaN
11,"Mystic Logistics, Inc. (10) (13)",Logistics and Distribution Services Provider f...,"12.00% Secured Debt (Maturity Date -August 15,...",2500,2430,2500.0
12,"Mystic Logistics, Inc. (10) (13)",Logistics and Distribution Services Provider f...,"Common Stock (1,468 shares)",680,1645.0,NaN
13,3110,4145.0,NaN,NaN,NaN,NaN
14,SoftTouch Medical Holdings LLC (8) (10) (13),Home Provider of Pediatric Durable Medical Equ...,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",1470,1444,1444.0
15,SoftTouch Medical Holdings LLC (8) (10) (13),Home Provider of Pediatric Durable Medical Equ...,Member Units (798 shares) (16),870,870.0,NaN
16,2314,2314.0,NaN,NaN,NaN,NaN
17,Subtotal Affiliate Investments (4) (1% of tota...,8702,9737.0,NaN,NaN,NaN
18,Non-Control/Non-Affiliate Investments (5),NaN,NaN,NaN,NaN,NaN
19,Ability Network Inc. (8),Health Care Information Technology,"LIBOR Plus 5.00% (Floor 1.00%), Current Coupon...",4950,4902.0,4971.0
20,Allflex Holdings III Inc. (8),Manufacturer of Livestock Identification Products,"LIBOR Plus 7.00% (Floor 1.00%), Current Coupon...",12422,12514,12519.0
21,"AmeriTech College Operations, LLC (10) (13)",For-Profit Nursing and Healthcare College,"10.00% Secured Debt, (Maturity - January 31, 2...",610,609,543.0
22,"AMF Bowling Centers, Inc. (8)",Bowling Alley Operator,"LIBOR Plus 6.25% (Floor 1.00%), Current Coupon...",10918,10826,10958.0
23,"AP Gaming I, LLC (8) (11)","Developer, Manufacturer, and Operator of Gamin...","LIBOR Plus 8.25% (Floor 1.00%), Current Coupon...",7481,7406,7471.0
24,"Aptean, Inc. (8)",Enterprise Application Software Provider,"LIBOR Plus 4.25% (Floor 1.00%), Current Coupon...",4438,4437,4399.0
25,"Arcus Hunting, LLC (8) (11)","Deer Lures, Attractants and Scent Elimination ...","LIBOR Plus 7.00% (Floor 1.00%), Current Coupon...",4933,4817,4817.0
26,"Artel, LLC (8)",Land-Based and Commercial Satellite Provider,"LIBOR Plus 6.00% (Floor 1.25%), Current Coupon...",4282,4172,4185.0
27,ATX Networks Corp. (8) (9) (12),Provider of Radio Frequency Management Equipment,"LIBOR Plus 6.00% (Floor 1.00%), Current Coupon...",15000,14700,14700.0
28,"Berry Aviation, Inc. (11)",Charter Airline Services,12.00% Current / 1.75% PIK Secured Debt (Matur...,1407,1384,1384.0
29,"Berry Aviation, Inc. (11)",Charter Airline Services,Common Stock (138 shares),100,100.0,NaN
30,1484,1484.0,NaN,NaN,NaN,NaN
31,"Bioventus, LLC (8) (11)",Production of Orthopedic Healing Products,"LIBOR Plus 10.00% (Floor 1.00%), Current Coupo...",7000,6877,7000.0
32,Blackbrush Oil and Gas LP (8),Oil & Gas Exploration,"LIBOR Plus 6.50% (Floor 1.00%), Current Coupon...",12085,11627,11224.0
33,Blackhawk Specialty Tools LLC (8) (12),Oilfield Equipment & Services,"LIBOR Plus 5.25% (Floor 1.25%), Current Coupon...",8639,8131,8380.0
34,Blue Bird Body Company (8),School Bus Manufacturer,"LIBOR Plus 5.50% (Floor 1.00%), Current Coupon...",5850,5775,5865.0
35,"Bluestem Brands, Inc. (8)",Multi-Channel Retailer of General Merchandise,"LIBOR Plus 7.50% (Floor 1.00%), Current Coupon...",6981,6725,6968.0
36,"Brightwood Capital Fund III, LP (9) (15)",Investment Partnership,"LP Interests (Brightwood Capital Fund III, LP)...",2825,2825.0,NaN
37,"Brundage-Bone Concrete Pumping, Inc.",Construction Services Provider,"10.38% Secured Bond (Maturity - September 1, 2...",4000,4045,4160.0
38,"Buca C, LLC (8) (10) (13)",Restaurants,"LIBOR Plus 7.25% (Floor 1.00%), Current Coupon...",16800,16464,16464.0
39,"Buca C, LLC (8) (10) (13)",Restaurants,Member Units (4 units),2400,2400.0,NaN
40,18864,18864.0,NaN,NaN,NaN,NaN

In [1110]:
new_col = pd_csv[pd_csv.isnull().sum(axis=1)==len(pd_csv.iloc[0])-1].iat[0,0]

In [1111]:
new_col

'Control Investments (6)'

In [1112]:
pd_csv = pd_csv.dropna(thresh=len(pd_csv.columns)-1)

In [1113]:
pd_csv

,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value
2,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0
3,"GRT Rubber Technologies, LLC (8) (10) (13)",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,NaN
7,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,11.00% Secured Debt (Maturity Date -November 7...,3040,2913.0,2913.0
8,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,Member Units (46 shares),300,300.0,NaN
9,"AFG Capital Group, LLC (10) (13)",Provider of Rent-to-Own Financing Solutions an...,Warrants (10 equivalent shares),65,65.0,NaN
...,...,...,...,...,...,...
143,"Volusion, LLC (10)",Provider of Online Software-as-a-Service e-Com...,"Warrants (407,408 equivalent shares)",600,600.0,NaN
145,"Worley Claims Services, LLC (8) (11)",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,6409,6500.0
146,YP Holdings LLC (8),Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,2687,2694.0
147,Subtotal Non-Control/Non-Affiliate Investments...,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",736957,729987.0,NaN
148,Total Investments,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",760090,754155.0,NaN

In [1114]:
for col in pd_csv.columns:
    pd_csv[col] = pd_csv[col].astype(str).str.replace(r"\(\d+\)","")

C:\Users\jaiso\AppData\Local\Temp\ipykernel_14052\749670804.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  pd_csv[col] = pd_csv[col].astype(str).str.replace(r"\(\d+\)","")

In [1115]:
pd_csv

,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value
2,"GRT Rubber Technologies, LLC",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0
3,"GRT Rubber Technologies, LLC",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,nan
7,"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,11.00% Secured Debt (Maturity Date -November 7...,3040,2913.0,2913.0
8,"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,Member Units (46 shares),300,300.0,nan
9,"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,Warrants (10 equivalent shares),65,65.0,nan
...,...,...,...,...,...,...
143,"Volusion, LLC",Provider of Online Software-as-a-Service e-Com...,"Warrants (407,408 equivalent shares)",600,600.0,nan
145,"Worley Claims Services, LLC",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,6409,6500.0
146,YP Holdings LLC,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,2687,2694.0
147,Subtotal Non-Control/Non-Affiliate Investments...,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",736957,729987.0,nan
148,Total Investments,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",760090,754155.0,nan

In [1116]:
pd_csv = pd_csv.fillna("")

In [1117]:
pd_csv.insert(0, 'Levels', new_col)

In [1118]:
pd_csv

,Levels,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value
2,Control Investments (6),"GRT Rubber Technologies, LLC",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0
3,Control Investments (6),"GRT Rubber Technologies, LLC",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,nan
7,Control Investments (6),"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,11.00% Secured Debt (Maturity Date -November 7...,3040,2913.0,2913.0
8,Control Investments (6),"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,Member Units (46 shares),300,300.0,nan
9,Control Investments (6),"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,Warrants (10 equivalent shares),65,65.0,nan
...,...,...,...,...,...,...,...
143,Control Investments (6),"Volusion, LLC",Provider of Online Software-as-a-Service e-Com...,"Warrants (407,408 equivalent shares)",600,600.0,nan
145,Control Investments (6),"Worley Claims Services, LLC",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,6409,6500.0
146,Control Investments (6),YP Holdings LLC,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,2687,2694.0
147,Control Investments (6),Subtotal Non-Control/Non-Affiliate Investments...,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",736957,729987.0,nan
148,Control Investments (6),Total Investments,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",760090,754155.0,nan

In [1119]:
pd_csv

,Levels,Portfolio Company (1) (3),Business Description,Type of Investment (2) (3),Principal (7),Cost (7),Fair Value
2,Control Investments (6),"GRT Rubber Technologies, LLC",Engineered Rubber Product Manufacturer,"LIBOR Plus 9.00% (Floor 1.00%), Current Coupon...",8147,7996.0,7996.0
3,Control Investments (6),"GRT Rubber Technologies, LLC",Engineered Rubber Product Manufacturer,"Member Units (2,896 shares)",6435,6435.0,nan
7,Control Investments (6),"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,11.00% Secured Debt (Maturity Date -November 7...,3040,2913.0,2913.0
8,Control Investments (6),"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,Member Units (46 shares),300,300.0,nan
9,Control Investments (6),"AFG Capital Group, LLC",Provider of Rent-to-Own Financing Solutions an...,Warrants (10 equivalent shares),65,65.0,nan
...,...,...,...,...,...,...,...
143,Control Investments (6),"Volusion, LLC",Provider of Online Software-as-a-Service e-Com...,"Warrants (407,408 equivalent shares)",600,600.0,nan
145,Control Investments (6),"Worley Claims Services, LLC",Insurance Adjustment Management and Services P...,"LIBOR Plus 8.00% (Floor 1.00%), Current Coupon...",6468,6409,6500.0
146,Control Investments (6),YP Holdings LLC,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",2678,2687,2694.0
147,Control Investments (6),Subtotal Non-Control/Non-Affiliate Investments...,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",736957,729987.0,nan
148,Control Investments (6),Total Investments,Online and Offline Advertising Operator,"LIBOR Plus 6.75% (Floor 1.25%), Current Coupon...",760090,754155.0,nan

In [1120]:
pd_csv.to_excel('HMS_invest-8.xlsx', index=None, header=True)

In [1121]:
!python --version

Python 3.9.12